# Generated by Django 5.1.5 on 2025-02-08 12:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='faqs.faq')),
            ],
            options={
                'indexes': [models.Index(fields=['language'], name='faqs_faqtra_languag_bb501a_idx')],
                'unique_together': {('faq', 'language')},
            },
        ),
    ]
