# Generated by Django 5.1.5 on 2025-02-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
